#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use Bin\Console;
use App\Components\Router\Printable;


$console = new Console($argv,$argc);
$printable = new Printable($console->run());
$printable->output();
